### ISSUE TITLE
error

### ISSUE THREAD

**Issue by maminsedghi** [SAFI174/tawakkul#3]
[{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/cache/prayer_time_cache.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'toJson' isn't defined for the type 'Coordinates'.\nTry correcting the name to the name of an existing method, or defining a method named 'toJson'.",
	"source": "dart",
	"startLineNumber": 52,
	"startColumn": 60,
	"endLineNumber": 52,
	"endColumn": 66
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/cache/prayer_time_cache.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'fromJson' isn't defined for the type 'Coordinates'.\nTry correcting the name to the name of an existing method, or defining a method named 'fromJson'.",
	"source": "dart",
	"startLineNumber": 61,
	"startColumn": 24,
	"endLineNumber": 61,
	"endColumn": 32
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/repository/quran_audio_playlist_repository.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameOnlyArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameOnlyArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 34,
	"startColumn": 23,
	"endLineNumber": 34,
	"endColumn": 51
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/repository/quran_audio_playlist_repository.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameOnlyArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameOnlyArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 35,
	"startColumn": 20,
	"endLineNumber": 35,
	"endColumn": 48
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/repository/quran_audio_playlist_repository.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameOnlyArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameOnlyArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 53,
	"startColumn": 25,
	"endLineNumber": 53,
	"endColumn": 53
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/repository/quran_audio_playlist_repository.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameOnlyArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameOnlyArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 54,
	"startColumn": 22,
	"endLineNumber": 54,
	"endColumn": 50
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/repository/quran_audio_playlist_repository.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameOnlyArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameOnlyArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 69,
	"startColumn": 25,
	"endLineNumber": 69,
	"endColumn": 53
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/data/repository/quran_audio_playlist_repository.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameOnlyArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameOnlyArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 70,
	"startColumn": 22,
	"endLineNumber": 70,
	"endColumn": 50
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/qibla_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_getter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_getter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The getter 'latitude' isn't defined for the type 'QiblahDirection'.\nTry importing the library that defines 'latitude', correcting the name to the name of an existing getter, or defining a getter or field named 'latitude'.",
	"source": "dart",
	"startLineNumber": 130,
	"startColumn": 63,
	"endLineNumber": 130,
	"endColumn": 71
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/qibla_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_getter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_getter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The getter 'longitude' isn't defined for the type 'QiblahDirection'.\nTry importing the library that defines 'longitude', correcting the name to the name of an existing getter, or defining a getter or field named 'longitude'.",
	"source": "dart",
	"startLineNumber": 135,
	"startColumn": 63,
	"endLineNumber": 135,
	"endColumn": 72
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/qibla_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_getter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_getter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The getter 'latitude' isn't defined for the type 'QiblahDirection'.\nTry importing the library that defines 'latitude', correcting the name to the name of an existing getter, or defining a getter or field named 'latitude'.",
	"source": "dart",
	"startLineNumber": 193,
	"startColumn": 63,
	"endLineNumber": 193,
	"endColumn": 71
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/qibla_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_getter",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_getter",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The getter 'longitude' isn't defined for the type 'QiblahDirection'.\nTry importing the library that defines 'longitude', correcting the name to the name of an existing getter, or defining a getter or field named 'longitude'.",
	"source": "dart",
	"startLineNumber": 198,
	"startColumn": 63,
	"endLineNumber": 198,
	"endColumn": 72
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_audio_download_manager_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getSurahNameOnlyArabicSimple' isn't defined for the type 'QuranAudioDownloadManagerPage'.\nTry correcting the name to the name of an existing method, or defining a method named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 203,
	"startColumn": 38,
	"endLineNumber": 203,
	"endColumn": 66
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_audio_download_manager_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unused_import",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unused_import",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 4,
	"message": "Unused import: 'package:quran/quran.dart'.\nTry removing the import directive.",
	"source": "dart",
	"startLineNumber": 6,
	"startColumn": 8,
	"endLineNumber": 6,
	"endColumn": 34
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_audio_player_settings_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getSurahNameOnlyArabicSimple' isn't defined for the type 'QuranAudioSettingsPage'.\nTry correcting the name to the name of an existing method, or defining a method named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 83,
	"startColumn": 28,
	"endLineNumber": 83,
	"endColumn": 56
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_audio_player_settings_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getSurahNameOnlyArabicSimple' isn't defined for the type 'QuranAudioSettingsPage'.\nTry correcting the name to the name of an existing method, or defining a method named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 113,
	"startColumn": 28,
	"endLineNumber": 113,
	"endColumn": 56
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_audio_player_settings_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getSurahNameOnlyArabicSimple' isn't defined for the type 'SurahAyahPicker'.\nTry correcting the name to the name of an existing method, or defining a method named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 376,
	"startColumn": 47,
	"endLineNumber": 376,
	"endColumn": 75
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_audio_player_settings_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "prefer_const_constructors",
		"target": {
			"$mid": 1,
			"path": "/lints/prefer_const_constructors",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Use 'const' with the constructor to improve performance.\nTry adding the 'const' keyword to the constructor invocation.",
	"source": "dart",
	"startLineNumber": 46,
	"startColumn": 13,
	"endLineNumber": 46,
	"endColumn": 20
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_reading_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getSurahNameOnlyArabicSimple' isn't defined for the type 'QuranPageHeader'.\nTry correcting the name to the name of an existing method, or defining a method named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 255,
	"startColumn": 23,
	"endLineNumber": 255,
	"endColumn": 51
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_reading_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getHizbText' isn't defined for the type 'QuranPageHeader'.\nTry correcting the name to the name of an existing method, or defining a method named 'getHizbText'.",
	"source": "dart",
	"startLineNumber": 267,
	"startColumn": 21,
	"endLineNumber": 267,
	"endColumn": 32
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_reading_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "deprecated_member_use",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/deprecated_member_use",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "'WillPopScope.new' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre.\nTry replacing the use of the deprecated member with the replacement.",
	"source": "dart",
	"startLineNumber": 33,
	"startColumn": 13,
	"endLineNumber": 33,
	"endColumn": 25,
	"tags": [
		2
	]
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/pages/quran_reading_page.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "deprecated_member_use",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/deprecated_member_use",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "'WillPopScope' is deprecated and shouldn't be used. Use PopScope instead. This feature was deprecated after v3.12.0-1.0.pre.\nTry replacing the use of the deprecated member with the replacement.",
	"source": "dart",
	"startLineNumber": 33,
	"startColumn": 13,
	"endLineNumber": 33,
	"endColumn": 25,
	"tags": [
		2
	]
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/utils/sheets/sheet_methods.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameArabicSimple'.",
	"source": "dart",
	"startLineNumber": 135,
	"startColumn": 56,
	"endLineNumber": 135,
	"endColumn": 80
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/utils/sheets/sheet_methods.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_cast",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unnecessary_cast",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary cast.\nTry removing the cast.",
	"source": "dart",
	"startLineNumber": 33,
	"startColumn": 33,
	"endLineNumber": 33,
	"endColumn": 71
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/views/hizb_list_view.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getHizbData' isn't defined for the type 'HizbListView'.\nTry correcting the name to the name of an existing method, or defining a method named 'getHizbData'.",
	"source": "dart",
	"startLineNumber": 31,
	"startColumn": 22,
	"endLineNumber": 31,
	"endColumn": 33
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/views/juz_list_view.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getJuzName' isn't defined for the type 'JuzListView'.\nTry correcting the name to the name of an existing method, or defining a method named 'getJuzName'.",
	"source": "dart",
	"startLineNumber": 20,
	"startColumn": 18,
	"endLineNumber": 20,
	"endColumn": 28
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/views/juz_list_view.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unused_import",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unused_import",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 4,
	"message": "Unused import: 'package:quran/quran.dart'.\nTry removing the import directive.",
	"source": "dart",
	"startLineNumber": 4,
	"startColumn": 8,
	"endLineNumber": 4,
	"endColumn": 34
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/views/juz_list_view.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "prefer_const_constructors",
		"target": {
			"$mid": 1,
			"path": "/lints/prefer_const_constructors",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Use 'const' with the constructor to improve performance.\nTry adding the 'const' keyword to the constructor invocation.",
	"source": "dart",
	"startLineNumber": 38,
	"startColumn": 17,
	"endLineNumber": 38,
	"endColumn": 27
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/views/surah_list_view.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getSurahNameArabicSimple' isn't defined.\nTry importing the library that defines 'getSurahNameArabicSimple', correcting the name to the name of an existing function, or defining a function named 'getSurahNameArabicSimple'.",
	"source": "dart",
	"startLineNumber": 18,
	"startColumn": 19,
	"endLineNumber": 18,
	"endColumn": 43
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/hizb_item.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getHizbData' isn't defined for the type 'HizbItem'.\nTry correcting the name to the name of an existing method, or defining a method named 'getHizbData'.",
	"source": "dart",
	"startLineNumber": 11,
	"startColumn": 22,
	"endLineNumber": 11,
	"endColumn": 33
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/juz_item.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_function",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_function",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The function 'getJuzNameQCF' isn't defined.\nTry importing the library that defines 'getJuzNameQCF', correcting the name to the name of an existing function, or defining a function named 'getJuzNameQCF'.",
	"source": "dart",
	"startLineNumber": 59,
	"startColumn": 31,
	"endLineNumber": 59,
	"endColumn": 44
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/juz_item.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "prefer_const_constructors",
		"target": {
			"$mid": 1,
			"path": "/lints/prefer_const_constructors",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Use 'const' with the constructor to improve performance.\nTry adding the 'const' keyword to the constructor invocation.",
	"source": "dart",
	"startLineNumber": 70,
	"startColumn": 30,
	"endLineNumber": 70,
	"endColumn": 48
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/surah_verse.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "undefined_method",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/undefined_method",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 8,
	"message": "The method 'getSurahNameOnlyArabicSimple' isn't defined for the type 'SurahVerseWidget'.\nTry correcting the name to the name of an existing method, or defining a method named 'getSurahNameOnlyArabicSimple'.",
	"source": "dart",
	"startLineNumber": 44,
	"startColumn": 13,
	"endLineNumber": 44,
	"endColumn": 41
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/surah_verse.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unused_import",
		"target": {
			"$mid": 1,
			"path": "/diagnostics/unused_import",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 4,
	"message": "Unused import: 'package:quran/quran.dart'.\nTry removing the import directive.",
	"source": "dart",
	"startLineNumber": 3,
	"startColumn": 8,
	"endLineNumber": 3,
	"endColumn": 34
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/surah_verse.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_brace_in_string_interps",
		"target": {
			"$mid": 1,
			"path": "/lints/unnecessary_brace_in_string_interps",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary braces in a string interpolation.\nTry removing the braces.",
	"source": "dart",
	"startLineNumber": 36,
	"startColumn": 20,
	"endLineNumber": 36,
	"endColumn": 28
},{
	"resource": "/C:/Users/Amin/Desktop/tawakkul-main/lib/widgets/surah_verse.dart",
	"owner": "_generated_diagnostic_collection_name_#1",
	"code": {
		"value": "unnecessary_brace_in_string_interps",
		"target": {
			"$mid": 1,
			"path": "/lints/unnecessary_brace_in_string_interps",
			"scheme": "https",
			"authority": "dart.dev"
		}
	},
	"severity": 2,
	"message": "Unnecessary braces in a string interpolation.\nTry removing the braces.",
	"source": "dart",
	"startLineNumber": 36,
	"startColumn": 29,
	"endLineNumber": 36,
	"endColumn": 37
}]

**Comment by SAFI174** [comment]
I am sorry but i forget to upload a custom package "quran" , i have made some local changes to it, i will fix it soon🙏👍

**Comment by SAFI174** [comment]
i have fix all this issue and push it, sorry for been late

**Comment by SAFI174** [comment]
i have fix all this issue and push it, sorry for been late

**Comment by aminsedghi2** [comment]
hi 
thank
