### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by masreplay** [SAFI174/tawakkul#4]
السلام عليكم
عاشت الايادي
في حال حصل عندك خطا برمجي او مشكلة الرجاء التواصل معي يمكنني مساعدتك❤️

**Comment by SAFI174** [comment]
وعليكم السلام
تسلم يارب وجزاك الله كل خير ❤️❤️

**Comment by masreplay** [comment]
السلام عليكم
هل المشروع مفتوح المصدر بالكامل اي يمكنني عمل تطبيق مختلف بستخدامه؟
وشكرا
