### ISSUE TITLE
not run.

### ISSUE THREAD

**Issue by SamadDev** [SAFI174/tawakkul#5]
<img width="1351" alt="Screenshot 2024-02-02 at 8 38 30 PM" src="https://github.com/SAFI174/tawakkul/assets/53392565/626b5df0-2674-4263-8175-08c36e07cb5e">
Hello, I have just cloned project with last Flutter SDK version and got all these errors.

**Comment by SAFI174** [comment]
i have fix all this issue and push it 😁

**Comment by SAFI174** [comment]
i have fix all this issue and push it
